const Our = [
  {
    id: 1,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://www.careerindia.com/img/2018/06/itsector-1528100471.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 2,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image:
      "https://images.indianexpress.com/2022/06/Untitled-design-2022-06-08T151015.621.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 3,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image:
      "https://www.freecodecamp.org/news/content/images/2022/01/home-office-g9d055a345_1280.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 4,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://kalingatv.com/wp-content/uploads/2020/02/IT-market.jpg",
    desc: "Dark king M2435 Mechanical keybord-free 31 key",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 4,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://kalingatv.com/wp-content/uploads/2020/02/IT-market.jpg",
    desc: "Dark king M2435 Mechanical keybord-free 31 key",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 5,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://www.careerindia.com/img/2018/06/itsector-1528100471.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 6,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image:
      "https://images.indianexpress.com/2022/06/Untitled-design-2022-06-08T151015.621.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 7,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image:
      "https://www.freecodecamp.org/news/content/images/2022/01/home-office-g9d055a345_1280.jpg",
    desc: "talented leaders now emerging in Saudi Arabia. That is why we have invested heavily in our Graduates Opportunities in Work (",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 8,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://kalingatv.com/wp-content/uploads/2020/02/IT-market.jpg",
    desc: "Dark king M2435 Mechanical keybord-free 31 key",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },
  {
    id: 9,
    name: "Dark king M2435 Mechanical keybord-free 31 key",
    image: "https://kalingatv.com/wp-content/uploads/2020/02/IT-market.jpg",
    desc: "Dark king M2435 Mechanical keybord-free 31 key",
    address: "New Delhi",
    price: 2344,
    sold: 12,
    rating: 4,
    tag: "laptop",
    location: "delhi",
  },

];
export default Our;